### ISSUE TITLE
Board outline is missing or malformed.

### ISSUE THREAD

**Issue by waymond91** [foostan/crkbd#111]
Fine work! I love the project and I'm super excited to build my own.
I am trying to generate gerber using KiCAD 5.99 however I cannot get the edge cuts to close. 
So that none of the 3d renderings by KiCad or manufacturers seem to come out correctly.
![image](https://user-images.githubusercontent.com/3513523/123508651-847f4780-d625-11eb-8517-cb6ee77d0267.png)
![image](https://user-images.githubusercontent.com/3513523/123508850-bcd35580-d626-11eb-8fb2-b9d9c190e44a.png)

Any advice would be great :)

**Comment by 641i130** [comment]
They still haven't solved this huh.

**Comment by foostan** [comment]
Thank you for reporting!
I fixed the classic, and cherry is no problem.
![image](https://user-images.githubusercontent.com/736191/130704855-37101be4-9fc1-472c-bd7f-ca5589f8c144.png)

Rendering results from some PCB vendors may not display correctly. For example, the display of jlcpcb is different from the result of kicad.

**Comment by LoyalPotato** [comment]
Hey, I'm still getting the pcb like the first picture in the issue.
I'm using kicad v6.0.1. When I open the plot menu, I get a 
> Global solder mask minimum width and/or margin are not set to 0. Most board manufacturers expect 0 and use their own constraints for solder mask minimum width.

I'm not sure if it has anything to do with the issue (I don't really know what it means, because I'm new to this, just trying out).
I generate the drill files and then plot.
Then upload the .zip into jlcpcb and it still shows with filled areas, like so:

![downImg](https://user-images.githubusercontent.com/10759876/153510766-b4c9547b-6841-4138-8dce-6fef8ac2e075.jpg)
